# Generated by Django 4.2.14 on 2024-07-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('mob_no', models.CharField(max_length=40)),
                ('address', models.TextField(max_length=500)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('dob', models.DateField()),
                ('skills', models.ManyToManyField(to='admin_app.skillchoice')),
            ],
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
