# Generated by Django 4.2.14 on 2024-07-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_profile_delete_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default=1234, max_length=200),
            preserve_default=False,
        ),
    ]
