# Generated by Django 4.2.14 on 2024-07-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(default=1234, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=1234, upload_to='profile_media'),
            preserve_default=False,
        ),
    ]
